version: "3.3"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.attack.rule=Host(`attack.wuhanstudio.uk`)"
        - "traefik.http.routers.attack.entrypoints=web"
        - "traefik.http.services.attack.loadbalancer.server.port=80"
        # TLS
        - "traefik.http.routers.attacks.rule=Host(`attack.wuhanstudio.uk`)"
        - "traefik.http.routers.attacks.entrypoints=websecure"
        - "traefik.http.routers.attacks.tls.certresolver=myhttpchallenge"
        # Redirect
        - "traefik.http.routers.attack.middlewares=https_redirect"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
